version: '3.8'

services:
  web:
    build: .
    command: sh -c "sleep 10 && python manage.py migrate && echo 'from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser(\"admin\", \"admin@gmail.com\", \"admin\")' | python manage.py shell && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 80:8000
    networks:
      - my-network
    env_file:
      - .env

volumes:
  postgres_data:

networks:
  my-network: